#!/bin/bash

echo "======================================"
echo "Configuration Base de Données MySQL"
echo "======================================"
echo ""
echo "Sur le VPS, exécutez ces commandes:"
echo ""
echo "ssh root@168.231.85.181"
echo ""
echo "# Créer la base de données et l'utilisateur"
echo "mysql -u root -p << 'EOSQL'"
echo "CREATE DATABASE IF NOT EXISTS letrousseau_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
echo "CREATE USER IF NOT EXISTS 'letrousseau_app'@'localhost' IDENTIFIED BY 'VOTRE_MOT_DE_PASSE_ICI';"
echo "GRANT SELECT, INSERT, UPDATE ON letrousseau_db.* TO 'letrousseau_app'@'localhost';"
echo "FLUSH PRIVILEGES;"
echo "SELECT 'Base de données créée' AS Status;"
echo "EOSQL"
echo ""
echo "# Créer la table submissions"
echo "mysql -u root -p letrousseau_db < /tmp/create-submissions-table.sql"
echo ""
echo "# Vérifier"
echo "mysql -u root -p -e \"USE letrousseau_db; SHOW TABLES; DESCRIBE submissions;\""
echo ""
